### PR TITLE
Add Candle

### PR DESCRIPTION
**Pull request by samisbakedham**

### CODE REVIEW

**Review by iower — APPROVED** [review]
Hi, thanks for your interest!

**Comment by samisbakedham** [comment]
> Hi, thanks for your interest!

Thank you for approving! Trying to integrate / add support for another chain on via, candle chain. What else is required, do you know?

**Review by nrjshka — APPROVED** [review]

**Comment by insulineru** [comment]
> > Hi, thanks for your interest!
> 
> Thank you for approving! Trying to integrate / add support for another chain on via, candle chain. What else is required, do you know?

Hi. Do you want to plug the network into our router? Are there already bridges that support the network?

**Comment by samisbakedham** [comment]
> > > Hi, thanks for your interest!
> 
> > 
> 
> > Thank you for approving! Trying to integrate / add support for another chain on via, candle chain. What else is required, do you know?
> 
> 
> 
> Hi. Do you want to plug the network into our router? Are there already bridges that support the network?
> 
> 

Hi, yes we do indeed. We're integrating with LiFi currently and Connext bridge, but currently there are only those.

**Pull request merged**
